# Generated by Django 5.0.2 on 2024-04-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_primera_app", "0003_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="nombre_del_equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
    ]
